runtime: java17
entrypoint: java -jar target/portfolio.jar

instance_class: F1

services:
  - type: web
    name: portfolio-vk
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/PortfolioVK.jar
    envVars:
      - key: JAVA_VERSION
        value: 17 
